- name: Install Node.js
  hosts: app_servers
  become: true

  tasks:
    - name: Install Node.js and npm
      dnf:
        name:
          - nodejs
          - npm
        state: present

    - name: Install Docker
      dnf:
        name: docker
        state: present

    - name: Start Docker
      service:
        name: docker
        state: started
        enabled: true

    - name: Add ec2-user to Docker group
      user:
        name: ec2-user
        groups: docker
        append: true